'use client';

import Link from 'next/link';
import { ArrowDown, ArrowUpRight, Activity, BarChart3, CalendarCheck, Camera, Camera as CameraIcon, CheckCircle2, CircleDot, Download, FileSpreadsheet, ShieldCheck, UserPlus, Users } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { ThemeToggle } from '@/components/shared/theme-toggle';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { LandingFooter } from './landing-footer';

const TRUSTED_LOGOS = [{ name: 'Nusantara', mark: 'N' }, { name: 'Maju Bersama', mark: 'MB' }, { name: 'Karya Digital', mark: 'KD' }, { name: 'Sinar Grup', mark: 'SG' }, { name: 'Padi Works', mark: 'PW' }, { name: 'Lestari Corp', mark: 'LC' }];
const HERO_HIGHLIGHTS = ['Verifikasi on-device', 'Cocok untuk tim HRD', 'Siap dipakai hari ini'];
const FEATURE_CELLS = [
  { icon: Camera, title: 'Absensi wajah on-device', description: 'Face-api.js berjalan di browser. Tidak ada upload foto, tidak ada roundtrip ke server.', specs: [{ k: 'threshold', v: '< 0.6' }, { k: 'verifikasi', v: '~120ms' }, { k: 'mode', v: 'offline-ready' }], span: 'md:col-span-2 md:row-span-2' },
  { icon: CalendarCheck, title: 'Cuti & izin', description: 'Pengajuan, saldo, dan arsip cuti dalam satu alur.', status: 'live', span: 'md:col-span-1' },
  { icon: ShieldCheck, title: 'Approval satu klik', description: 'HRD setujui atau tolak langsung dari dashboard.', status: 'live', span: 'md:col-span-1' },
  { icon: Activity, title: 'Notifikasi realtime', description: 'Socket.io menyiarkan event tanpa refresh halaman.', status: 'beta', span: 'md:col-span-2' },
];
const HOW_STEPS = [
  { n: '01', icon: UserPlus, title: 'Daftarkan wajah karyawan', body: 'Sekali saat onboarding. Face descriptor disimpan di database terenkripsi.' },
  { n: '02', icon: CameraIcon, title: 'Karyawan selfie saat presensi', body: 'Verifikasi berjalan lokal di browser lewat face-api.js.' },
  { n: '03', icon: Download, title: 'HRD tinjau lalu ekspor', body: 'Filter berdasarkan tanggal, departemen, status. Ekspor ke XLSX kapan saja.' },
];
const PORTAL_FEATURES = {
  karyawan: ['Dashboard status kehadiran hari ini', 'Pengajuan cuti dan lembur dari mobile', 'Lacak sisa kuota cuti tahunan', 'Lihat histori presensi 30 hari terakhir'],
  hrd: ['Rekap presensi real-time lintas kantor', 'Approval cuti dan lembur dalam satu antrian', 'Manajemen data karyawan dan departemen', 'Ekspor laporan bulanan ke XLSX'],
};
const DARK_STATS = [{ v: '2.4k', l: 'karyawan aktif' }, { v: '99.2%', l: 'akurasi verifikasi' }, { v: '3.8k', l: 'presensi per bulan' }, { v: '12 mnt', l: 'hemat waktu HRD per hari' }];

function Reveal({ children, className }: { children: React.ReactNode; delay?: number; className?: string }) {
  return <div className={className}>{children}</div>;
}

function LogoMark({ name, mark }: { name: string; mark: string }) {
  return <div className="flex items-center gap-2 text-muted-foreground hover:text-foreground transition-colors" aria-label={name} title={name}><span className="w-7 h-7 rounded-md border border-border bg-card flex items-center justify-center text-[10px] font-bold tracking-tight">{mark}</span><span className="text-sm font-medium tracking-tight">{name}</span></div>;
}

function HeroPreview() {
  const stats = [['Hadir', '184'], ['Izin', '12'], ['Telat', '4']];
  const rows = [{ n: 'Aulia Pratiwi', t: '08:01', s: 'hadir' }, { n: 'Rizky Hidayat', t: '08:14', s: 'hadir' }, { n: 'Dewi Anggraini', t: '09:02', s: 'telat' }];
  return <Card className="shadow-elev-lg border-border/70 bg-card/90 backdrop-blur-sm"><CardHeader className="pb-3"><div className="flex items-center justify-between"><CardTitle as="h2" className="text-section">Dashboard HRD</CardTitle><span className="text-[11px] font-mono uppercase tracking-wider text-muted-foreground">contoh</span></div><CardDescription>Rekap presensi hari ini</CardDescription></CardHeader><CardContent className="space-y-4"><div className="grid grid-cols-3 gap-2">{stats.map(([label, value]) => <div key={label} className="rounded-lg border border-border bg-background/60 p-3"><p className="text-[10px] uppercase tracking-wider text-muted-foreground font-mono">{label}</p><p className="text-title text-data text-foreground leading-none mt-1.5">{value}</p></div>)}</div><div className="space-y-2">{rows.map((row) => <div key={row.n} className="flex items-center justify-between rounded-md border border-border/60 bg-background/40 px-3 py-2"><div className="flex items-center gap-2.5"><CircleDot className={`w-3.5 h-3.5 ${row.s === 'telat' ? 'text-warning' : 'text-success'}`} /><span className="text-sm text-foreground">{row.n}</span></div><span className="text-xs font-mono text-data text-muted-foreground">{row.t}</span></div>)}</div><div className="flex items-center gap-2 pt-1"><FileSpreadsheet className="w-3.5 h-3.5 text-muted-foreground" /><span className="text-xs text-muted-foreground">Ekspor laporan bulanan</span></div></CardContent></Card>;
}

export function LandingPage({ year }: { year: number }) {
  return <div className="min-h-screen bg-background text-foreground">
    <nav className="sticky top-0 z-40 bg-background/80 backdrop-blur-xl border-b border-border/60"><div className="max-w-6xl mx-auto flex items-center justify-between px-4 sm:px-6 h-16"><Link href="/" className="flex items-center gap-2.5"><div className="w-8 h-8 rounded-lg gradient-brand flex items-center justify-center shadow-elev-sm"><span className="text-white font-bold text-xs tracking-tight">HR</span></div><span className="font-semibold text-foreground tracking-tight">Smart HRMS</span><span className="hidden sm:inline-flex items-center rounded-md border border-border bg-muted px-1.5 py-0.5 text-[10px] font-mono uppercase tracking-wider text-muted-foreground">Beta</span></Link><div className="flex items-center gap-2"><ThemeToggle /><Button asChild size="sm" className="gap-1"><Link href="/login">Masuk <ArrowUpRight className="w-3.5 h-3.5" /></Link></Button></div></div></nav>

    <section className="px-4 sm:px-6 pt-12 sm:pt-16 pb-12 sm:pb-16"><div className="max-w-6xl mx-auto grid grid-cols-1 md:grid-cols-12 gap-10 md:gap-8 items-center"><Reveal className="md:col-span-7 space-y-5"><p className="text-xs font-mono uppercase tracking-[0.2em] text-primary">HRMS · Indonesia</p><h1 className="text-[2.5rem] sm:text-5xl md:text-6xl font-semibold tracking-tighter leading-[1.05] text-foreground text-balance">Presensi wajah, cuti, dan lembur <span className="text-primary">dalam satu platform.</span></h1><p className="text-base sm:text-lg text-muted-foreground leading-relaxed max-w-[58ch]">Smart HRMS menggabungkan verifikasi wajah, alur approval, dan laporan untuk tim HRD Indonesia.</p><div className="flex flex-wrap items-center gap-3"><Button asChild variant="gradient" size="xl" className="gap-1.5"><Link href="/login">Masuk ke aplikasi <ArrowUpRight className="w-4 h-4" /></Link></Button><Button asChild variant="ghost" size="xl" className="gap-1.5"><a href="#fitur">Pelajari fitur <ArrowDown className="w-4 h-4" /></a></Button></div><p className="text-xs text-muted-foreground">Cocok untuk tim 50–500 orang · tanpa instalasi tambahan</p></Reveal><Reveal delay={0.12} className="md:col-span-5"><HeroPreview /></Reveal></div></section>

    <section className="border-y border-border/60 bg-card/40"><div className="max-w-6xl mx-auto px-4 sm:px-6 py-5"><ul className="flex flex-wrap items-center justify-center gap-x-6 gap-y-2 text-sm text-muted-foreground">{HERO_HIGHLIGHTS.map((h) => <li key={h} className="inline-flex items-center gap-1.5"><CheckCircle2 className="w-4 h-4 text-success" />{h}</li>)}</ul></div></section>

    <section className="py-12 sm:py-14 px-4 sm:px-6"><div className="max-w-6xl mx-auto"><p className="text-center text-sm text-muted-foreground">Dipakai tim HRD di berbagai perusahaan</p><div className="mt-6 flex flex-wrap items-center justify-center gap-x-8 gap-y-4">{TRUSTED_LOGOS.map((l) => <LogoMark key={l.name} name={l.name} mark={l.mark} />)}</div><p className="mt-6 text-center text-xs text-muted-foreground">Diuji di lingkungan produksi sejak 2024</p></div></section>

    <section id="fitur" className="py-16 sm:py-24 px-4 sm:px-6"><div className="max-w-6xl mx-auto"><Reveal className="max-w-[55ch]"><p className="text-xs font-mono uppercase tracking-[0.2em] text-primary">Fitur inti</p><h2 className="mt-2 text-title sm:text-[1.75rem] font-semibold tracking-tight text-foreground">Empat hal yang dipakai HRD tiap hari.</h2><p className="mt-3 text-sm text-muted-foreground leading-relaxed">Dari presensi sampai notifikasi, semua alur kerja hadir dalam satu ruang operasional.</p></Reveal><div className="mt-10 grid grid-cols-1 md:grid-cols-4 auto-rows-[minmax(180px,auto)] gap-4">{FEATURE_CELLS.map((f, i) => { const Icon = f.icon; const isHero = i === 0; return <Reveal key={f.title} delay={i * 0.05} className={`relative rounded-2xl border border-border p-6 flex flex-col gap-4 overflow-hidden hover:-translate-y-0.5 hover:shadow-elev-lg transition-all duration-300 ${f.span} ${isHero ? 'gradient-mesh bg-card' : 'bg-card'}`}><div className={`w-11 h-11 rounded-xl flex items-center justify-center text-white shadow-elev-sm ${isHero ? 'gradient-brand' : 'bg-foreground'}`}><Icon className="w-5 h-5" /></div><div><h3 className="text-section text-foreground">{f.title}</h3><p className="mt-1.5 text-sm text-muted-foreground leading-relaxed">{f.description}</p></div>{isHero && f.specs ? <div className="mt-auto grid grid-cols-3 gap-2 pt-2">{f.specs.map((s) => <div key={s.k} className="rounded-lg border border-border/60 bg-background/60 p-2.5"><p className="text-[10px] uppercase tracking-wider text-muted-foreground font-mono">{s.k}</p><p className="text-sm font-mono tabular-nums text-foreground mt-1">{s.v}</p></div>)}</div> : <span className="mt-auto self-start rounded-full border border-border/70 bg-background/60 px-2 py-1 text-[10px] font-mono uppercase tracking-wider text-muted-foreground">{f.status}</span>}</Reveal>; })}</div></div></section>

    <section className="py-16 sm:py-24 px-4 sm:px-6 border-t border-border/60"><div className="max-w-6xl mx-auto grid grid-cols-1 md:grid-cols-12 gap-10"><Reveal className="md:col-span-4"><p className="text-xs font-mono uppercase tracking-[0.2em] text-primary">Alur kerja</p><h2 className="mt-2 text-title sm:text-[1.75rem] font-semibold tracking-tight text-foreground">Cara kerja singkat.</h2><p className="mt-3 text-sm text-muted-foreground leading-relaxed max-w-[40ch]">Tiga langkah dari onboarding sampai laporan bulanan. Tidak perlu berpindah tools.</p><Button asChild variant="link" className="mt-4 h-auto px-0"><a href="#cta">Lihat alur lengkap <ArrowUpRight className="w-4 h-4" /></a></Button></Reveal><div className="md:col-span-8 divide-y divide-border/60">{HOW_STEPS.map((s, i) => { const Icon = s.icon; return <Reveal key={s.n} delay={i * 0.06}><div className="py-5 flex items-start gap-5"><span className="text-2xl font-mono tabular-nums text-muted-foreground leading-none pt-1 w-10 shrink-0">{s.n}</span><div className="w-10 h-10 rounded-xl border border-border bg-card flex items-center justify-center shrink-0"><Icon className="w-5 h-5 text-primary" /></div><div className="flex-1"><h3 className="text-section text-foreground">{s.title}</h3><p className="mt-1 text-sm text-muted-foreground leading-relaxed">{s.body}</p></div></div></Reveal>; })}</div></div></section>

    <section className="py-16 sm:py-24 px-4 sm:px-6 border-t border-border/60 bg-card/30"><div className="max-w-6xl mx-auto"><Reveal className="max-w-[60ch]"><p className="text-xs font-mono uppercase tracking-[0.2em] text-primary">Dua pengalaman</p><h2 className="mt-2 text-title sm:text-[1.75rem] font-semibold tracking-tight text-foreground">Satu platform, dua peran.</h2><p className="mt-3 text-sm text-muted-foreground leading-relaxed">Portal berbeda untuk karyawan dan HRD, dari satu basis data yang sama.</p></Reveal><div className="mt-10 grid grid-cols-1 md:grid-cols-2 gap-4"><Reveal><Card className="h-full bg-card border-border"><CardHeader><div className="flex items-center gap-2.5"><div className="w-9 h-9 rounded-lg bg-primary/10 text-primary flex items-center justify-center"><Users className="w-4 h-4" /></div><CardTitle as="h3" className="text-section">Portal Karyawan</CardTitle></div><CardDescription>Akses dari mobile atau desktop. Self-service untuk hal yang berulang.</CardDescription></CardHeader><CardContent><ul className="divide-y divide-border/40">{PORTAL_FEATURES.karyawan.map((f) => <li key={f} className="flex items-start gap-2.5 py-2.5 text-sm text-foreground"><CheckCircle2 className="w-4 h-4 text-success shrink-0 mt-0.5" /><span>{f}</span></li>)}</ul><Button asChild variant="soft" size="sm" className="mt-5"><Link href="/login?role=karyawan">Buka portal <ArrowUpRight className="w-3.5 h-3.5" /></Link></Button></CardContent></Card></Reveal><Reveal delay={0.06}><Card className="h-full bg-card border-border"><CardHeader><div className="flex items-center gap-2.5"><div className="w-9 h-9 rounded-lg bg-primary/10 text-primary flex items-center justify-center"><BarChart3 className="w-4 h-4" /></div><CardTitle as="h3" className="text-section">Portal HRD</CardTitle></div><CardDescription>Dashboard operasional. Data real-time, ekspor satu klik.</CardDescription></CardHeader><CardContent><ul className="divide-y divide-border/40">{PORTAL_FEATURES.hrd.map((f) => <li key={f} className="flex items-start gap-2.5 py-2.5 text-sm text-foreground"><CheckCircle2 className="w-4 h-4 text-success shrink-0 mt-0.5" /><span>{f}</span></li>)}</ul><Button asChild variant="soft" size="sm" className="mt-5"><Link href="/login?role=hrd">Buka portal <ArrowUpRight className="w-3.5 h-3.5" /></Link></Button></CardContent></Card></Reveal></div></div></section>

    <section className="px-4 sm:px-6 py-14 sm:py-16"><div className="max-w-6xl mx-auto rounded-2xl gradient-brand-deep overflow-hidden shadow-elev-lg"><p className="pt-6 text-center text-xs uppercase tracking-[0.2em] text-white/70 font-mono">Angka yang bicara</p><div className="grid grid-cols-2 md:grid-cols-4 divide-y md:divide-y-0 md:divide-x divide-white/10">{DARK_STATS.map((s) => <div key={s.l} className="p-6 sm:p-8"><p className="text-3xl sm:text-4xl font-semibold tracking-tighter text-white font-mono tabular-nums leading-none">{s.v}</p><p className="mt-2 text-xs text-white/70 uppercase tracking-wider">{s.l}</p></div>)}</div></div></section>

    <section id="cta" className="py-16 sm:py-24 px-4 sm:px-6"><div className="max-w-2xl mx-auto text-center"><Reveal><p className="text-xs font-mono uppercase tracking-[0.2em] text-primary">Mulai dari sini</p><h2 className="mt-2 text-title sm:text-[1.75rem] font-semibold tracking-tight text-foreground">Coba dengan akun demo hari ini.</h2><p className="mt-3 text-muted-foreground max-w-[50ch] mx-auto">Masuk dengan kredensial demo yang sudah disiapkan. Tanpa setup, tanpa instalasi.</p><div className="mt-7"><Button asChild variant="gradient" size="xl" className="gap-1.5"><Link href="/login">Masuk ke aplikasi <ArrowUpRight className="w-4 h-4" /></Link></Button></div><p className="mt-4 text-xs text-muted-foreground">Tanpa setup · dua akun demo siap pakai</p></Reveal></div></section>
    <LandingFooter year={year} />
  </div>;
}
